### PR TITLE
Link against GLFW dll instead of static

### PR DESCRIPTION
**Pull request by plooshi**

### CODE REVIEW

**Comment by CMDR-JohnAlex** [comment]
What would linking against vs static glfw do?

**Review by Piras314 — COMMENTED** [review]
Looks good, nice.

**Comment by plooshi** [comment]
@CMDR-JohnAlex static bundles inside the program, so the file size is bigger. but a dll (or a shared library) can be used by multiple programs in memory, but would require distributing multiple files or having them on path.

**Review by Piras314 — APPROVED** [review]

**Comment by CMDR-JohnAlex** [comment]
When adding these changes to my local branch it seems that the dll will need to be included with the exe.
Personally I don't like having the dll files needing to be packaged with the exe.
The main problem is there are two dlls, 32 bit and 64 bit dlls. If you build 32 bit you will need to move the 32 bit dll to the project root (where the exe is) and when you want to run 64 bit you will need to delete the 32 bit dll and copy the 64 bit dll.

I will however merge #6 because 64-bit support is a good addition.

**Pull request closed without merging**
